const fs = require('fs');

// 1. FIX CAKES.HTML
let cakes = fs.readFileSync('cakes.html', 'utf8');
cakes = cakes.replace('<button class="dakingo-btn">Order Here</button>', '<button class="dakingo-btn" onclick="addToCart(\\\'Dakingo Signature Chocolate\\\', 999, \\\'cake_category_1777660447849.png\\\', 1); openCheckout();">Order Here</button>');
cakes = cakes.replace('<div class="flavor-circle">\\n                <div class="img-wrap"><img src="recommended_cake.png" alt="Vanilla"></div>\\n                <h4>Vanilla Bean</h4>\\n            </div>', '<div class="flavor-circle" onclick="openProductModal(\\\'Vanilla Bean Cake\\\', \\\'A classic smooth vanilla bean cake.\\\', 599, \\\'recommended_cake.png\\\')">\\n                <div class="img-wrap"><img src="recommended_cake.png" alt="Vanilla"></div>\\n                <h4>Vanilla Bean</h4>\\n            </div>');
cakes = cakes.replace('<div class="flavor-circle">\\n                <div class="img-wrap"><img src="blueberry_cheesecake_1784385282085.png" alt="Strawberry"></div>\\n                <h4>Strawberry</h4>\\n            </div>', '<div class="flavor-circle" onclick="openProductModal(\\\'Strawberry Cake\\\', \\\'Fresh strawberry bliss.\\\', 649, \\\'blueberry_cheesecake_1784385282085.png\\\')">\\n                <div class="img-wrap"><img src="blueberry_cheesecake_1784385282085.png" alt="Strawberry"></div>\\n                <h4>Strawberry</h4>\\n            </div>');
cakes = cakes.replace('<div class="flavor-circle">\\n                <div class="img-wrap"><img src="cake_category_1777660447849.png" alt="Caramel"></div>\\n                <h4>Salted Caramel</h4>\\n            </div>', '<div class="flavor-circle" onclick="openProductModal(\\\'Salted Caramel Cake\\\', \\\'Decadent salted caramel layers.\\\', 749, \\\'cake_category_1777660447849.png\\\')">\\n                <div class="img-wrap"><img src="cake_category_1777660447849.png" alt="Caramel"></div>\\n                <h4>Salted Caramel</h4>\\n            </div>');
fs.writeFileSync('cakes.html', cakes);

// 2. FIX PASTRIES.HTML
let pastries = fs.readFileSync('pastries.html', 'utf8');
pastries = pastries.replace('<button class="croissant-btn">Order Pickup</button>', '<button class="croissant-btn" onclick="addToCart(\\\'Artisan Berry Croissant\\\', 249, \\\'elegant_croissant_1784385566982.png\\\', 1); openCheckout();">Order Pickup</button>');
pastries = pastries.replace('<div class="special-card" style="background: #e8ded6;">\\n                <img src="croissant_splash_1784385246079.png" alt="Croissant">\\n                <h4>Golden Classic<br>Croissant</h4>\\n            </div>', '<div class="special-card" style="background: #e8ded6;" onclick="openProductModal(\\\'Golden Classic Croissant\\\', \\\'Flaky buttery goodness.\\\', 149, \\\'croissant_splash_1784385246079.png\\\')">\\n                <img src="croissant_splash_1784385246079.png" alt="Croissant">\\n                <h4>Golden Classic<br>Croissant</h4>\\n            </div>');
pastries = pastries.replace('<div class="special-card" style="background: #dcdbd3;">\\n                <img src="blueberry_cheesecake_1784385282085.png" alt="Dessert">\\n                <h4>Berry Cheesecake<br>Delight</h4>\\n            </div>', '<div class="special-card" style="background: #dcdbd3;" onclick="openProductModal(\\\'Berry Cheesecake Delight\\\', \\\'A perfect slice of berry cheesecake.\\\', 299, \\\'blueberry_cheesecake_1784385282085.png\\\')">\\n                <img src="blueberry_cheesecake_1784385282085.png" alt="Dessert">\\n                <h4>Berry Cheesecake<br>Delight</h4>\\n            </div>');
pastries = pastries.replace('<div class="special-card" style="background: #e0c8b6;">\\n                <img src="pastry_category_1777660510169.png" alt="Pastry">\\n                <h4>Caramel Pear<br>Hazelnut Pastry</h4>\\n            </div>', '<div class="special-card" style="background: #e0c8b6;" onclick="openProductModal(\\\'Hazelnut Pastry\\\', \\\'Rich caramel and hazelnut flavors.\\\', 199, \\\'pastry_category_1777660510169.png\\\')">\\n                <img src="pastry_category_1777660510169.png" alt="Pastry">\\n                <h4>Caramel Pear<br>Hazelnut Pastry</h4>\\n            </div>');
fs.writeFileSync('pastries.html', pastries);

// 3. FIX ICECREAM.HTML
let icecream = fs.readFileSync('icecream.html', 'utf8');
icecream = icecream.replace('<button style="background:#fff; color:#ff758c; padding:15px 35px; border-radius:30px; font-weight:bold; border:none; cursor:pointer; font-size:1.1rem; box-shadow:0 10px 20px rgba(0,0,0,0.1);">Order Now</button>', '<button style="background:#fff; color:#ff758c; padding:15px 35px; border-radius:30px; font-weight:bold; border:none; cursor:pointer; font-size:1.1rem; box-shadow:0 10px 20px rgba(0,0,0,0.1);" onclick="addToCart(\\\'Sweetest Delights Ice Cream\\\', 349, \\\'blueberry_cone_1784385590123.png\\\', 1); openCheckout();">Order Now</button>');
icecream = icecream.replace('<div class="ice-card">\\n                <img src="icecream_category_1777660485890.png" alt="Vanilla">\\n                <h3>Vanilla Almond</h3>\\n                <p>Classic vanilla bean with roasted almonds in a waffle cone.</p>\\n            </div>', '<div class="ice-card" onclick="openProductModal(\\\'Vanilla Almond Ice Cream\\\', \\\'Classic vanilla bean with roasted almonds in a waffle cone.\\\', 199, \\\'icecream_category_1777660485890.png\\\')">\\n                <img src="icecream_category_1777660485890.png" alt="Vanilla">\\n                <h3>Vanilla Almond</h3>\\n                <p>Classic vanilla bean with roasted almonds in a waffle cone.</p>\\n            </div>');
icecream = icecream.replace('<div class="ice-card">\\n                <img src="recommended_icecream.png" alt="Mango">\\n                <h3>Tropical Mango</h3>\\n                <p>Fresh mango gelato bursting with summer flavors.</p>\\n            </div>', '<div class="ice-card" onclick="openProductModal(\\\'Tropical Mango Gelato\\\', \\\'Fresh mango gelato bursting with summer flavors.\\\', 229, \\\'recommended_icecream.png\\\')">\\n                <img src="recommended_icecream.png" alt="Mango">\\n                <h3>Tropical Mango</h3>\\n                <p>Fresh mango gelato bursting with summer flavors.</p>\\n            </div>');
icecream = icecream.replace('<div class="ice-card">\\n                <img src="strawberry_splash_1784385077502.png" alt="Strawberry">\\n                <h3>Berry Burst</h3>\\n                <p>Strawberry and raspberry swirl for the ultimate berry lover.</p>\\n            </div>', '<div class="ice-card" onclick="openProductModal(\\\'Berry Burst Sundae\\\', \\\'Strawberry and raspberry swirl for the ultimate berry lover.\\\', 259, \\\'strawberry_splash_1784385077502.png\\\')">\\n                <img src="strawberry_splash_1784385077502.png" alt="Strawberry">\\n                <h3>Berry Burst</h3>\\n                <p>Strawberry and raspberry swirl for the ultimate berry lover.</p>\\n            </div>');
fs.writeFileSync('icecream.html', icecream);

// 4. FIX COFFEE.HTML
let coffee = fs.readFileSync('coffee.html', 'utf8');
coffee = coffee.replace('<button class="drinks-btn">Learn more</button>', '<button class="drinks-btn" onclick="addToCart(\\\'Signature Iced Coffee\\\', 199, \\\'iced_coffee_splash_1784385065567.png\\\', 1); openCheckout();">Buy Now</button>');
fs.writeFileSync('coffee.html', coffee);

console.log('Fixed all buttons!');
